### ISSUE TITLE
500 foutmelding bij opslaan zaaktype

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#1070]
**General information**
Open Zaak version: 1.3.5

**Describe the bug**
Een 500 foutmelding toont als ik een nieuw zaaktype wil 'Opslaan en opnieuw bewerken'. Onder andere getest vandaag om 13.23u

In omgeving: https://saxion-sandbox-openzaak.projecten.contezza.nl/admin/catalogi/zaaktype/add/?_changelist_filters=catalogus__id__exact%3D1

**To Reproduce**
1. Ga naar https://saxion-sandbox-openzaak.projecten.contezza.nl
2. Log in met admin
3. Ga naar Catalogi
4. Kies 'Toon zaaktypen' van de catalogus 'Saxion Content'
5. Kies 'Zaaktype toevoegen'
6. Vul minstens alle verplichte velden in
7. Klik op 'Opslaan en opnieuw bewerken'
8. 500 foutmelding interal error toont

**Expected behavior**
Op dit moment zou het zaaktype moeten opslaan en opnieuw getoond moeten worden om te bewerken. De gedeelten voor zaaktypenrelaties, statustypen, roltypen, eigenschappen en resultaattypen zouden nu ook bewerkbaar moeten worden.

**Comment by sergei-maertens** [comment]
hi Olav, thanks for the bug report!

Do you have any Sentry or container logs/tracebacks available?

**Comment by OlavAllema** [comment]
Ik heb dit voor je Sergei:

2021-11-24 12:54:58,298 ERROR django.request  Internal Server Error: /admin/catalogi/zaaktype/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "./openzaak/utils/admin.py", line 349, in add_view
    extra_context=self._get_extra_context(request, extra_context),
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "./openzaak/components/catalogi/admin/zaaktypen.py", line 321, in save_model
    super().save_model(request, obj, form, change)
  File "./openzaak/components/catalogi/admin/mixins.py", line 452, in save_model
    viewset.notify(status_code=200, data=data, instance=obj)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 169, in notify
    raise RuntimeError("Could not build a client for Notifications API")
RuntimeError: Could not build a client for Notifications API

**Comment by OlavAllema** [comment]
@sergei-maertens Kan je een update geven over dit ticket? We kunnen nu namelijk niet in Open Zaak werken hierdoor

**Comment by sergei-maertens** [comment]
hi @OlavAllema 

het lijkt erop dat je de Notificaties API niet of niet correct geconfigureerd hebt. Een notificaties API is een harde requirement van Open Zaak.

Kan je me tonen wat de config test op `https://jullie.openzaak.domein//view-config/` zegt? Zolang niet alle vinkjes groen zijn op die testpagina is Open Zaak in principe niet correct geconfigureerd.

**Comment by OlavAllema** [comment]
Dank Sergei, voor je uitleg en antwoord. Er kunnen inmiddels zaaktypen worden aangemaakt. Wat we nog wel hebben is de volgende foutmelding:
![image](https://user-images.githubusercontent.com/75848616/144082538-6da2574b-1081-4ecc-ade1-365649097237.png)

Wat is hiervan het gevolg? Kan je ons daarbij helpen?

**Comment by sergei-maertens** [comment]
Open Notificaties controleert of applicaties rechten hebben om notificaties te publiceren of consumeren. Notificaties worden gerouteerd op kanalen, en de Open Zaak configuratietest verifieert dus of Open Zaak publicatierechten heeft door de beschikbare op te vragen bij Open Notificaties.

Dit gaat hier fout - zo te zien is Open Zaak niet geautoriseerd hiervoor. Deze autorisaties stel je in Open Zaak zelf in (of een alternatieve Autorisaties API als je die gebruikt). Als dit in Open Zaak zelf al goed staan, dan kan je in Open Notificaties proberen de cache weg te gooien: Open Notificaties > admin > API Autorisaties > Applicaties en dan de Open Zaak autorisatie verwijderen.

Deze stappen gaan ervan uit dat je de rest van de Open Zaak/Open Notificaties configuratie al uitgevoerd hebt.

**Comment by OlavAllema** [comment]
Dank voor alle antwoorden Sergei
