### ISSUE TITLE
Setting an archived archivation status on case creation results in a 500 error

### ISSUE THREAD

**Issue by rjzondervan** [open-zaak/open-zaak#1108]
**General information**
Open Zaak version:  1.4.0

**Describe the bug**
When setting the archivation status of a case when creating the case to an 'archived' status like `gearchiveerd_procestermijn_onbekend`, the 'zaken'-API responds with a 500 error, I'll add the traceback at the bottom of the issue.

**To Reproduce**
1. Import the openapi.json of the 'zaken'-API into Postman
2. Select the 'Create a ZAAK'-request in the resulting collection
3. Clean up the data by removing or replacing invalid urls, data in the past etc. but not the `archiefstatus` field, this should be `gearchiveerd_procestermijn_onbekend`
4. Run the request

**Expected behavior**
A 400 error that describes that you cannot create a case with an 'archived' status like `gearchiveerd_procestermijn_onbekend`, from which the user can deduce that something is amiss on their side.

**Additional Information**
_Traceback of the resulting error_
```ERROR vng_api_common.views  'NoneType' object has no attribute 'zaakinformatieobject_set'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 206, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/audittrails/viewsets.py", line 100, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 421, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 454, in run_validators
    super().run_validators(to_validate)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 593, in run_validators
    validator(value)
  File "./openzaak/components/zaken/api/validators.py", line 182, in __call__
    self.validate_local_eios_archived(attrs, documents_not_archived_error)
  File "./openzaak/components/zaken/api/validators.py", line 191, in validate_local_eios_archived
    canonical_ids = self.instance.zaakinformatieobject_set.values(
AttributeError: 'NoneType' object has no attribute 'zaakinformatieobject_set'
2022-03-07 14:35:56,179 ERROR vng_api_common.views  'NoneType' object has no attribute 'zaakinformatieobject_set'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 206, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/audittrails/viewsets.py", line 100, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 421, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 454, in run_validators
    super().run_validators(to_validate)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 593, in run_validators
    validator(value)
  File "./openzaak/components/zaken/api/validators.py", line 182, in __call__
    self.validate_local_eios_archived(attrs, documents_not_archived_error)
  File "./openzaak/components/zaken/api/validators.py", line 191, in validate_local_eios_archived
    canonical_ids = self.instance.zaakinformatieobject_set.values(
AttributeError: 'NoneType' object has no attribute 'zaakinformatieobject_set'
2022-03-07 14:35:56,180 ERROR vng_api_common.exception_handling  Exception 580df3c0-f27d-4aca-a7f2-af5f2099b299 ocurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 206, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/audittrails/viewsets.py", line 100, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 421, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 454, in run_validators
    super().run_validators(to_validate)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 593, in run_validators
    validator(value)
  File "./openzaak/components/zaken/api/validators.py", line 182, in __call__
    self.validate_local_eios_archived(attrs, documents_not_archived_error)
  File "./openzaak/components/zaken/api/validators.py", line 191, in validate_local_eios_archived
    canonical_ids = self.instance.zaakinformatieobject_set.values(
AttributeError: 'NoneType' object has no attribute 'zaakinformatieobject_set'
2022-03-07 14:35:56,180 ERROR vng_api_common.exception_handling  Exception 580df3c0-f27d-4aca-a7f2-af5f2099b299 ocurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 206, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/audittrails/viewsets.py", line 100, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 421, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 454, in run_validators
    super().run_validators(to_validate)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 593, in run_validators
    validator(value)
  File "./openzaak/components/zaken/api/validators.py", line 182, in __call__
    self.validate_local_eios_archived(attrs, documents_not_archived_error)
  File "./openzaak/components/zaken/api/validators.py", line 191, in validate_local_eios_archived
    canonical_ids = self.instance.zaakinformatieobject_set.values(
AttributeError: 'NoneType' object has no attribute 'zaakinformatieobject_set'```

**Comment by sergei-maertens** [comment]
Thank you! From the traceback my suspicion is that some serializer-level validation runs on a field that was was already invalidated earlier (and is therefore not available in the serializer data).
