### ISSUE TITLE
API Schema traceback

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#1120]
**General information**
Open Zaak version: latest (after the Django 3.2 upgrade)

**Describe the bug**

Traceback: 

```
2022-03-23 14:45:53,525 ERROR django.request  Internal Server Error: /zaken/api/v1/schema/openapi.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/drf_yasg/views.py", line 44, in _wrapped_view_func
    response.add_post_render_callback(callback)
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 92, in add_post_render_callback
    callback(self)
  File "/usr/local/lib/python3.7/site-packages/drf_yasg/views.py", line 41, in callback
    add_never_cache_headers(response)
  File "/usr/local/lib/python3.7/site-packages/django/utils/cache.py", line 274, in add_never_cache_headers
    patch_response_headers(response, cache_timeout=-1)
  File "/usr/local/lib/python3.7/site-packages/django/utils/cache.py", line 265, in patch_response_headers
    if not response.has_header('Expires'):
  File "/usr/local/lib/python3.7/site-packages/django/http/response.py", line 182, in has_header
    return header in self.headers
AttributeError: 'Response' object has no attribute 'headers'
```

**To Reproduce**
1. Start container
2. Request the Zaken API schema

**Expected behavior**

No errors should be visible

**Comment by sergei-maertens** [comment]
Currently not able to easily reproduce this in development mode

**Comment by sergei-maertens** [comment]
I can also no longer see this happening in the logs of the deployed containers - it may have had something to do with the cached version of an earlier version of Django that was not compatible with the Django 3.2 based version.

I will add to the release notes that on deploy, it's recommended to flush caches, and reopen this issue if it occurs again.
