### ISSUE TITLE
External DRC: informatieobject service unknown

### ISSUE THREAD

**Issue by rderooij** [open-zaak/open-zaak#1332]
**General information**
Open Zaak version: 1.8.1

**Describe the bug**
We are upgrading from 1.7.4 to 1.8.1 and we encounter problems when adding 'zaakinformatieobjecten'. We are using an external DRC and we get the following error.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8048477/217850005-5344d928-d3fc-4b84-bf06-0e9d11a1b7e5.png">

Post:
```
{
    "beschrijving": "Aanvulling",
    "informatieobject": "http://tezza-services-platform.local:8080/alfresco/service/drc/v1/enkelvoudiginformatieobjecten/d2f9fd2c-77bd-4100-8cfa-c99ef692d1a1",
    "titel": "Test",
    "zaak": "http://tezza-openzaak.local:8000/zaken/api/v1/zaken/8b68a80b-2696-426b-b1e1-0946b37ab346"
}
```

Error:
```
2023-02-09 14:34:40,128 WARNING django.request  Bad Request: /zaken/api/v1/zaakinformatieobjecten
2023-02-09 15:34:40 [pid: 58|app: 0|req: 141/256] 10.201.0.1 () {42 vars in 855 bytes} [Thu Feb  9 14:34:39 2023] POST /zaken/api/v1/zaakinformatieobjecten => generated 309 bytes in 266 msecs (HTTP/1.1 400) 9 headers in 275 bytes (1 switches on core 1)
2023-02-09 15:36:41 2023-02-09 14:36:41,750 ERROR vng_api_common.exception_handling  Exception 7cedb8f4-ad02-4952-9b7b-ce7f040ba222 ocurred
2023-02-09 15:36:41 Traceback (most recent call last):
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-02-09 15:36:41     response = handler(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/notifications_api_common/viewsets.py", line 189, in create
2023-02-09 15:36:41     response = super().create(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/vng_api_common/audittrails/viewsets.py", line 110, in create
2023-02-09 15:36:41     response = super().create(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
2023-02-09 15:36:41     serializer.is_valid(raise_exception=True)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 228, in is_valid
2023-02-09 15:36:41     raise ValidationError(self.errors)
2023-02-09 15:36:41 rest_framework.exceptions.ValidationError: {'informatieobject': [ErrorDetail(string='De service voor deze URL is niet bekend.', code='unknown-service')]}
2023-02-09 15:36:41 2023-02-09 14:36:41,750 ERROR vng_api_common.exception_handling  Exception 7cedb8f4-ad02-4952-9b7b-ce7f040ba222 ocurred
2023-02-09 15:36:41 Traceback (most recent call last):
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-02-09 15:36:41     response = handler(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/notifications_api_common/viewsets.py", line 189, in create
2023-02-09 15:36:41     response = super().create(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/vng_api_common/audittrails/viewsets.py", line 110, in create
2023-02-09 15:36:41     response = super().create(request, *args, **kwargs)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
2023-02-09 15:36:41     serializer.is_valid(raise_exception=True)
2023-02-09 15:36:41   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 228, in is_valid
2023-02-09 15:36:41     raise ValidationError(self.errors)
2023-02-09 15:36:41 rest_framework.exceptions.ValidationError: {'informatieobject': [ErrorDetail(string='De service voor deze URL is niet bekend.', code='unknown-service')]}
2023-02-09 15:36:41 2023-02-09 14:36:41,751 WARNING django.request  Bad Request: /zaken/api/v1/zaakinformatieobjecten
2023-02-09 15:36:41 Bad Request: /zaken/api/v1/zaakinformatieobjecten
2023-02-09 15:36:41 2023-02-09 14:36:41,751 WARNING django.request  Bad Request: /zaken/api/v1/zaakinformatieobjecten
```

**Comment by OlavAllema** [comment]
@joeribekker Kunnen jullie een reactie plaatsen hierop? Wij willen uiteraard graag (met klanten) richting 1.8. Daarvoor is dit issue voor ons essentieel (dat je het weet)

**Comment by joeribekker** [comment]
Ik vermoed dat dit komt door #1209. Zoals in de Changelog staat van 1.8.0:

> [#1209] URL references to external data (e.g. external documenten API) are now normalized:
>   You must define an external Service for each external API that is used
>   If the external service changes their base URL, you only need to update the service
>   Provides foundation for future support for mTLS-based services

Als dit om een externe (buiten Open Zaak) URL gaat dan moet je die configureren. Als het niet om een externe URL gaat dan is het inderdaad een bug. Laat maar even weten.

**Comment by rderooij** [comment]
Could you please elaborate on this? Because the explanation you referring to makes no sense for me. Prior to 1.8.0 you also needed to add an external service to communicate to (in my case) an external DRC. I have looked at the configuration in Open Zaak when adding a new service and I cannot see any other configuration settings that is different to version 1.7.4. 

What do I need to configure in 1.8.2 that is different to version 1.7.4 and can you validate if this issue is indeed a bug?

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/8048477/225313598-b1814a90-fda7-4391-abe4-96fe36d5d8b1.png">
