### ISSUE TITLE
Loading a fixture with a document does not create the corresponding file on disk

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#1711]
### Product versie / Product version

1.13.0

### Omschrijf het probleem / Describe the bug

If I load a fixture with a document, and then I make a request to delete that document through the API, I get a 500 error.

The logs show this stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/app/src/./openzaak/utils/decorators.py", line 53, in convert_exceptions
    response = function(*args, **kwargs)
  File "/app/src/./openzaak/utils/mixins.py", line 77, in destroy
    return super().destroy(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/notifications_api_common/viewsets.py", line 205, in destroy
    instance = self.get_object()
  File "/usr/local/lib/python3.10/site-packages/rest_framework/generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/app/src/./openzaak/utils/permissions.py", line 188, in has_object_permission
    main_object_data = self.format_data(main_object, request)
  File "/app/src/./openzaak/utils/permissions.py", line 50, in format_data
    return serializer.data
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/app/src/./openzaak/components/documenten/api/serializers.py", line 546, in to_representation
    ret = super().to_representation(instance)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/app/src/./openzaak/components/documenten/api/serializers.py", line 115, in to_representation
    file.file
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 48, in _get_file
    self._file = self.storage.open(self.name, "rb")
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage/base.py", line 22, in open
    return self._open(name, mode)
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 68, in _open
    return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/private-media/uploads/2024/07/file_QaYarsY.bin'
```

### Stappen om te reproduceren / Steps to reproduce

I used this docker compose file: https://github.com/maykinmedia/open-archiefbeheer/blob/12fb45921c988bbe0408191eddda38f5ca12e6ef/backend/docker-services/openzaak/docker-compose.yaml
With this fixture: 
[data.json](https://github.com/user-attachments/files/16159509/data.json)

When making a DELETE request to `/documenten/api/v1/enkelvoudiginformatieobjecten/e3ed6b86-b226-4dc0-bfd7-3858646083fc` I get a 500 error. 

If I look in the container, the `/app/private-media` directory is empty.

### Verwacht gedrag / Expected behavior

A 204 response.

**Comment by joeribekker** [comment]
Refinement: This fixture is not the way to add documents to Open Zaak. You can leave out the `inhoud` of use `link` to add a hyperlink to anywhere. Or use the import endpoint for documents that we recently added.

**Comment by joeribekker** [comment]
@SilviaAmAm please let me know what you think.

**Comment by SilviaAmAm** [comment]
Thank you! I am wondering, maybe it would also be good to not raise an error if the file is not found on disk? In that way it also wouldn't matter if the files are not created for the fixtures :thinking:
