### ISSUE TITLE
500 error in admin when non-required fields are not filled in

### ISSUE THREAD

**Issue by shea-maykinmedia** [open-zaak/open-zaak#467]
While adding stuff in the admin I noticed that I would occasionally get a 500 error if I didn't fill in a non-required field.  It seems mostly related to not specifying a type for certain instances.

One example is when adding a _Besluit_ through the admin screen there will be a 500 error if _Besluittype_ isn't specified.  The error is because this entry can not be null on the database level but is not required in the admin screen.

To prevent these error I think these fields should be marked as required in the admin screen (or possibly make it not required on a database level).

Here is an example stack trace of the example I listed
```python
web_1    | 2020-02-06 15:18:05,429 ERROR django.request  Internal Server Error: /admin/besluiten/besluit/add/
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | psycopg2.errors.CheckViolation: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
web_1    | 
web_1    | 
web_1    | The above exception was the direct cause of the following exception:
web_1    | 
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
web_1    |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
web_1    |     return view(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
web_1    |     return self.changeform_view(request, None, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1    |     return bound_method(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
web_1    |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
web_1    |     self.save_model(request, new_object, form, not add)
web_1    |   File "./openzaak/utils/admin.py", line 210, in save_model
web_1    |     super().save_model(request, obj, form, change)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
web_1    |     obj.save()
web_1    |   File "./openzaak/components/besluiten/models.py", line 191, in save
web_1    |     super().save(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
web_1    |     force_update=force_update, update_fields=update_fields)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
web_1    |     force_update, using, update_fields,
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
web_1    |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
web_1    |     using=using, raw=raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
web_1    |     return query.get_compiler(using=using).execute_sql(return_id)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
web_1    |     cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
web_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
web_1    |     return executor(sql, params, many, context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | django.db.utils.IntegrityError: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
web_1    | 
web_1    | 2020-02-06 15:18:05,429 ERROR django.request  Internal Server Error: /admin/besluiten/besluit/add/
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | psycopg2.errors.CheckViolation: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
web_1    | 
web_1    | 
web_1    | The above exception was the direct cause of the following exception:
web_1    | 
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
web_1    |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
web_1    |     return view(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
web_1    |     return self.changeform_view(request, None, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1    |     return bound_method(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
web_1    |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
web_1    |     self.save_model(request, new_object, form, not add)
web_1    |   File "./openzaak/utils/admin.py", line 210, in save_model
web_1    |     super().save_model(request, obj, form, change)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
web_1    |     obj.save()
web_1    |   File "./openzaak/components/besluiten/models.py", line 191, in save
web_1    |     super().save(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
web_1    |     force_update=force_update, update_fields=update_fields)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
web_1    |     force_update, using, update_fields,
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
web_1    |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
web_1    |     using=using, raw=raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
web_1    |     return query.get_compiler(using=using).execute_sql(return_id)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
web_1    |     cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
web_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
web_1    |     return executor(sql, params, many, context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | django.db.utils.IntegrityError: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
web_1    | 
web_1    | 2020-02-06 15:18:05,429 ERROR django.request  Internal Server Error: /admin/besluiten/besluit/add/
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | psycopg2.errors.CheckViolation: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
web_1    | 
web_1    | 
web_1    | The above exception was the direct cause of the following exception:
web_1    | 
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
web_1    |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
web_1    |     return view(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
web_1    |     return self.changeform_view(request, None, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1    |     return bound_method(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
web_1    |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
web_1    |     self.save_model(request, new_object, form, not add)
web_1    |   File "./openzaak/utils/admin.py", line 210, in save_model
web_1    |     super().save_model(request, obj, form, change)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
web_1    |     obj.save()
web_1    |   File "./openzaak/components/besluiten/models.py", line 191, in save
web_1    |     super().save(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
web_1    |     force_update=force_update, update_fields=update_fields)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
web_1    |     force_update, using, update_fields,
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
web_1    |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
web_1    |     using=using, raw=raw)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
web_1    |     return query.get_compiler(using=using).execute_sql(return_id)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
web_1    |     cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
web_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
web_1    |     return executor(sql, params, many, context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | django.db.utils.IntegrityError: new row for relation "besluiten_besluit" violates check constraint "_besluittype_or__besluittype_url_filled"
web_1    | DETAIL:  Failing row contains (1, ed7bd64f-4668-4783-a464-9b8951c87e2e, BESLUIT-2020-0000000001, 002220647, , , 2020-02-06, , , 2020-02-06, null, , null, null, null, , null, 3).
```

**Comment by shea-maykinmedia** [comment]
I can't seem to change the label or assignee.  I'm not sure if how important we want to consider this but I thought it was worth documenting an issue so it's not forgotten about. :)

**Comment by joeribekker** [comment]
Hey, Shea!

Nice catch. It's good to see that if someone actually works with it, all sorts of issues pop up.
Since you run into these, can you discuss quickly with Sergei and fix them? :)

**Comment by shea-maykinmedia** [comment]
👍

**Comment by shea-maykinmedia** [comment]
Fix with https://github.com/open-zaak/open-zaak/pull/472
