### ISSUE TITLE
Command register_kanaal doesn't work

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#665]
**Describe the bug**
When trying to run `register_kanaal zaken` it returns an error.

**To Reproduce**
```
# docker exec -it openzaak-0 src/manage.py register_kanaal zaken
b"''"
2020-07-30 10:32:16,972 ERROR sentry.errors.serializer  ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/local/lib/python3.7/site-packages/zds_client/config.py", line 22, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self.base_url)
  File "/usr/local/lib/python3.7/site-packages/zds_client/config.py", line 50, in base_url
    default_port = default_ports[self.scheme]
KeyError: ''
Traceback (most recent call last):
  File "src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/management/commands/register_kanaal.py", line 80, in handle
    create_kanaal(api_root, kanaal)
  File "/usr/local/lib/python3.7/site-packages/vng_api_common/notifications/management/commands/register_kanaal.py", line 30, in create_kanaal
    client = Client.from_url(api_root)
  File "/usr/local/lib/python3.7/site-packages/zds_client/client.py", line 156, in from_url
    config = ClientConfig.from_url(detail_url)
  File "/usr/local/lib/python3.7/site-packages/zds_client/config.py", line 40, in from_url
    return cls.from_dict({"scheme": parsed_url.scheme, "host": host, "port": port})
  File "/usr/local/lib/python3.7/site-packages/zds_client/config.py", line 28, in from_dict
    return cls(**_config, auth=auth)
  File "/usr/local/lib/python3.7/site-packages/zds_client/config.py", line 18, in __init__
    self.port = port if port else default_ports[scheme]
KeyError: ''
```

**Expected behavior**
It should create the kanaal zaken.

Workaround is to create them in the admin.

**Comment by sergei-maertens** [comment]
Ran into this again, but now because of permission errors.

The command is provided by `vng_api_common`, and is still hardcoded on using the `APICredential` model. However, we use `zgw_consumers` now for external service configuration. The management command needs to be adapted to use the setting that was introduced earlier to fetch the credentials from zgw_consumers instead of `APICredential` model.

The workaround is adding the credentials to the database model, but this is very technical and essentially looks whack.

**Comment by sergei-maertens** [comment]
Was fixed via https://github.com/VNG-Realisatie/vng-api-common/commit/dcb66b61540468a9b1ae53345a4f20a2e764315d#diff-27e81d2aacc6bb8423b5682cc18c7f9fe84ee90f2f4b1c2357bb165f1975c4a1 in vng-api-common 1.0.52 and we are currently on `vng-api-common==1.0.57`

**Comment by sergei-maertens** [comment]
And duplicated by https://github.com/open-zaak/open-zaak/issues/738
