### ISSUE TITLE
Occasional test error

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#770]
**Describe the bug**
Test https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/components/besluiten/tests/models/test_bio_block_change_cmis.py#L36
occasionally fails with the following stacktrace:

```
Traceback (most recent call last):
  File "/home/travis/build/open-zaak/open-zaak/src/openzaak/components/documenten/query/cmis.py", line 529, in create
    content=content,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/drc_cmis/client.py", line 147, in update_document
    cmis_doc = self.get_document(drc_uuid)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/drc_cmis/browser/client.py", line 427, in get_document
    return extract_latest_version(self.document_type, json_response.get("results"))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/drc_cmis/utils/utils.py", line 75, in extract_latest_version
    raise does_not_exist
drc_cmis.utils.exceptions.DocumentDoesNotExistError: Document bestaat niet in het CMIS connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/open-zaak/open-zaak/src/openzaak/components/besluiten/tests/models/test_bio_block_change_cmis.py", line 22, in setUp
    eio = EnkelvoudigInformatieObjectFactory.create(identificatie="12345")
  File "/home/travis/build/open-zaak/open-zaak/src/openzaak/components/documenten/tests/factories.py", line 60, in create
    return super().create(**kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/base.py", line 564, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/django.py", line 141, in _generate
    return super(DjangoModelFactory, cls)._generate(strategy, params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/base.py", line 501, in _generate
    return step.build()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/base.py", line 315, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/factory/django.py", line 185, in _create
    return manager.create(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/travis/build/open-zaak/open-zaak/src/openzaak/components/documenten/query/cmis.py", line 536, in create
    content=content,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/drc_cmis/browser/client.py", line 326, in create_document
    self.check_document_exists(identification)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/drc_cmis/browser/client.py", line 444, in check_document_exists
    raise DocumentExistsError(error_string)
drc_cmis.utils.exceptions.DocumentExistsError: Document identificatie 12345 is niet uniek.
```

The `setUp()` for the test creates a new document with `identificatie` "12345".
However, the stacktrace shows that a document with `identificatie` "12345" already exists.
This means that the clean-up of previous tests sometimes does not work as expected.

**To Reproduce**
Running tests on Travis multiple times...

**Expected behavior**
When the document is created there should be no other documents in the DMS, so no error should be raised.

**Comment by sergei-maertens** [comment]
Can reopen when this happens again, it's improved a lot with recent PRs
