### ISSUE TITLE
Deleting a Zaak related to a document fails

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#951]
**General information**
Trying to delete a zaak related to a document through the API returns a 500 error. This was seen with CMIS enabled and WEBSERVICE binding. Deleting the zaak through the Admin works.

**To Reproduce**
POST to `zaken/api/v1/zaken` to create a new zaak
POST to `documenten/api/v1/enkelvoudiginformatieobjecten` to create a new document
POST to  `zaken/api/v1/zaakinformatieobjecten` to create a new ZIO
DELETE to the URL of the zaak created above

The error:
```
Traceback (most recent call last):
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/vng_api_common/notifications/viewsets.py", line 228, in destroy
    return response
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/silvia/repositories/open-zaak/env/lib/python3.7/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/home/silvia/repositories/open-zaak/src/openzaak/components/zaken/api/viewsets.py", line 312, in _delete_oios
    client.delete("objectinformatieobject", url=url)
AttributeError: 'NoneType' object has no attribute 'delete'
2021-04-14 14:56:05,771 ERROR django.server  "DELETE /zaken/api/v1/zaken/e532493e-3a05-4515-b9b1-d014d936d2c3 HTTP/1.1" 500 35607
```

**Expected behavior**
Should give a 204 response.

**Comment by sergei-maertens** [comment]
Afaik the behaviour from the standard is that a validation error should be raised, because the relations must be broken first before you can delete the zaak itself. Though this *might* be part of the cascading delete, can you check with reference implementation?

**Comment by SilviaAmAm** [comment]
@sergei-maertens If I understand [this discussion](https://github.com/VNG-Realisatie/gemma-zaken/issues/791) correctly, I think you are right. If there is a relation, the relation should be broken first. But in the `perform_destroy()` I only see a mention of relations with besluiten (https://github.com/maykinmedia/gemma-zaakregistratiecomponent/blob/master/src/zrc/api/viewsets.py#L280)

**Comment by sergei-maertens** [comment]
looking at the tests, it looks like only
https://github.com/maykinmedia/gemma-zaakregistratiecomponent/blob/master/src/zrc/api/tests/test_zaken.py#L734
is covered as well.

The textual description is clear though:
https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index#zrc-023

The ZIO delete is a cascade delete that's implicit.
