### ISSUE TITLE
Server throws exception when setting up Open Zaak with CMIS_ENABLED=True

### ISSUE THREAD

**Issue by bartjkdp** [open-zaak/open-zaak#972]
**General information**
Open Zaak version: 1.4.0

**Describe the bug**

Starting up a new instance of Open Zaak that did not run the migrations previously with `CMIS_ENABLED=True`, will throw the following exception:

```bash
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "drc_cmis_cmisconfig" does not exist
LINE 1: ...", "drc_cmis_cmisconfig"."other_folder_path" FROM "drc_cmis_...
^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "src/manage.py", line 26, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
django.setup()
File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
app_config.import_models()
File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
self.models_module = import_module(models_module_name)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/src/openzaak/components/documenten/models.py", line 277, in <module>
AuditTrailMixin, APIMixin, InformatieObject, CMISClientMixin
File "/app/src/openzaak/components/documenten/models.py", line 324, in EnkelvoudigInformatieObject
upload_to="uploads/%Y/%m/", storage=private_media_storage_cmis
File "/usr/local/lib/python3.7/site-packages/privates/fields.py", line 9, in __init__
super().__init__(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/files.py", line 226, in __init__
self.storage = storage or default_storage
File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
self._setup()
File "/app/src/openzaak/components/documenten/utils.py", line 122, in _setup
self._wrapped = CMISStorage()
File "/app/src/openzaak/components/documenten/utils.py", line 63, in __init__
self._client = get_cmis_client()
File "/usr/local/lib/python3.7/site-packages/drc_cmis/client_builder.py", line 23, in get_cmis_client
config = CMISConfig.get_solo()
File "/usr/local/lib/python3.7/site-packages/solo/models.py", line 54, in get_solo
obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
return self.get(**kwargs), False
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
num = len(clone)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
self._fetch_all()
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
self._result_cache = list(self._iterable_class(self))
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "drc_cmis_cmisconfig" does not exist
LINE 1: ...", "drc_cmis_cmisconfig"."other_folder_path" FROM "drc_cmis_...
^
```

**To Reproduce**

1. Run `helm install -n open-zaak open-zaak/open-zaak --set image.tag=1.4.0 --set settings.cmis.enabled=true` on a clean cluster
2. The server will not boot, but throw the exception.

Setting up a new instance with `settings.cmis.enabled=false` will work. Migrations will run correctly and switching on CMIS after the migrations have run works.

**Expected behavior**

Setting up a new instance of Open Zaak with `settings.cmis.enabled=true` should work without throwing an exception.

**Comment by sergei-maertens** [comment]
Thanks for the clear bug report! This should be fixed indeed :)
